[package]
name = "case2geojson"
version = "0.1.0"
edition = "2021"

[dependencies]
geojson = "0.24.1"
iref = "3.2.2"
json-ld = { git = "https://github.com/miterst/json-ld.git", rev = "6b48152595b661ae5ada46747e15f373e698d151" }
oxigraph = { version = "0.4.1", default-features = false}
serde_json = "1.0.135"
static-iref = "3.0.0"
tokio = { version = "1.48.0", features = ["macros", "rt-multi-thread", "test-util"] }
